IDI_APPICO              equ 3020        ; иконка приложения
IDR_TABBMP              equ 3021        ; иконки для tab control

DLG_LOGINFO             equ 3000
IDC_LIST                equ 3009
IDC_OK                  equ 3011
IDC_REFRESH             equ 3012
IDC_REPORT              equ 3013
IDC_DATAFROM            equ 3005
IDC_DATATO              equ 3006
IDC_TIMEFROM            equ 3007
IDC_TIMETO              equ 3008
IDC_OBJECT              equ 3004
IDC_RTR                 equ 3014


IDD_DIALOG1 = 2010

IDOK1    = 2002
IDOK2    = 2003
IDOK3    = 2004
IDOK4    = 2005
IDOK5    = 2006
IDC_STATIC = 2007



