ifndef @unicode
    else
endif ; @unicode

procdesc gluBeginCurve            :DWORD
procdesc gluBeginPolygon          :DWORD
procdesc gluBeginSurface          :DWORD
procdesc gluBeginTrim             :DWORD
procdesc gluBuild1DMipmaps        :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluBuild2DMipmaps        :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluCylinder              :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluDeleteNurbsRenderer   :DWORD
procdesc gluDeleteQuadric         :DWORD
procdesc gluDeleteTess            :DWORD
procdesc gluDisk                  :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluEndCurve              :DWORD
procdesc gluEndPolygon            :DWORD
procdesc gluEndSurface            :DWORD
procdesc gluEndTrim               :DWORD
procdesc gluErrorString           :DWORD
procdesc gluErrorUnicodeStringEXT :DWORD
procdesc gluGetNurbsProperty      :DWORD,:DWORD,:DWORD
procdesc gluGetString             :DWORD
procdesc gluGetTessProperty       :DWORD,:DWORD,:DWORD
procdesc gluLoadSamplingMatrices  :DWORD,:DWORD,:DWORD,:DWORD
procdesc gluLookAt                :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluNewNurbsRenderer      
procdesc gluNewQuadric            
procdesc gluNewTess               
procdesc gluNextContour           :DWORD,:DWORD
procdesc gluNurbsCallback         :DWORD,:DWORD,:DWORD
procdesc gluNurbsCurve            :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluNurbsProperty         :DWORD,:DWORD,:DWORD
procdesc gluNurbsSurface          :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluOrtho2D               :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluPartialDisk           :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluPerspective           :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluPickMatrix            :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluProject               :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluPwlCurve              :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluQuadricCallback       :DWORD,:DWORD,:DWORD
procdesc gluQuadricDrawStyle      :DWORD,:DWORD
procdesc gluQuadricNormals        :DWORD,:DWORD
procdesc gluQuadricOrientation    :DWORD,:DWORD
procdesc gluQuadricTexture        :DWORD,:DWORD
procdesc gluScaleImage            :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluSphere                :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluTessBeginContour      :DWORD
procdesc gluTessBeginPolygon      :DWORD,:DWORD
procdesc gluTessCallback          :DWORD,:DWORD,:DWORD
procdesc gluTessEndContour        :DWORD
procdesc gluTessEndPolygon        :DWORD
procdesc gluTessNormal            :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc gluTessProperty          :DWORD,:DWORD,:DWORD,:DWORD
procdesc gluTessVertex            :DWORD,:DWORD,:DWORD
procdesc gluUnProject             :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
