ifndef @unicode
    else
endif ; @unicode

procdesc OleCreateFontIndirect          :DWORD,:DWORD,:DWORD
procdesc OleCreatePictureIndirect       :DWORD,:DWORD,:DWORD,:DWORD
procdesc OleCreatePropertyFrame         :DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc OleCreatePropertyFrameIndirect :DWORD
procdesc OleIconToCursor                :DWORD,:DWORD
procdesc OleLoadPicture                 :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc OleTranslateColor              :DWORD,:DWORD,:DWORD
procdesc _OleCreateFontIndirect         :DWORD,:DWORD,:DWORD
