ifndef @unicode
    else
endif ; @unicode

procdesc RasAdminCompressPhoneNumber  :DWORD,:DWORD
procdesc RasAdminDLLInit              :DWORD,:DWORD,:DWORD
procdesc RasAdminFreeBuffer           :DWORD
procdesc RasAdminGetErrorString       :DWORD,:DWORD,:DWORD
procdesc RasAdminGetUserAccountServer :DWORD,:DWORD,:DWORD
procdesc RasAdminGetUserParms         :DWORD,:DWORD
procdesc RasAdminPortClearStatistics  :DWORD,:DWORD
procdesc RasAdminPortDisconnect       :DWORD,:DWORD
procdesc RasAdminPortEnum             :DWORD,:DWORD,:DWORD
procdesc RasAdminPortGetInfo          :DWORD,:DWORD,:DWORD,:DWORD,:DWORD
procdesc RasAdminServerGetInfo        :DWORD,:DWORD
procdesc RasAdminSetUserParms         :DWORD,:DWORD,:DWORD
procdesc RasAdminUserGetInfo          :DWORD,:DWORD,:DWORD
procdesc RasAdminUserSetInfo          :DWORD,:DWORD,:DWORD
